apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bi-course-dev

namePrefix: dev-

commonLabels:
  environment: dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployments-patch.yaml

replicas:
  - name: auth-service
    count: 1
  - name: course-command-service
    count: 1
  - name: course-query-service
    count: 1
