apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployments/infrastructure.yaml
  - services/auth-service.yaml
  - services/course-command-service.yaml
  - services/course-query-service.yaml
  - services/infrastructure-services.yaml
  - services/zookeeper-service.yaml
  - storage/

namespace: bi-course
