apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bi-course-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: api.bi-course.local
      http:
        paths:
          # All API traffic goes through API Gateway
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bi-api-gateway-service
                port:
                  number: 80
    - host: app.bi-course.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: course-ui
                port:
                  number: 80
