apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  profile: dev

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  url: jdbc:postgresql://dev-postgres:5432/bi_course_db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  host: dev-mongodb
  port: "27017"
  database: bi_course_db

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  bootstrap-servers: dev-kafka:9092

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  host: dev-redis
